### ISSUE TITLE
We could throw some ✨algorithms and data structures✨ magic on here to decrease the complexity of graph traversal

### ISSUE THREAD

**Issue by Bluerberry** [PRIME-TU-Delft/graaf-svelte-4#30]
We could throw some ✨algorithms and data structures✨ magic on here to decrease the complexity of graph traversal

Though honestly, I don't think we'll have much problems with performance, considering the graphs are pretty small. Might be nice to look at _at some point_, but definitely not a priority at the moment :)

_Originally posted by @juliavdkris in https://github.com/PRIME-TU-Delft/graaf/pull/28#discussion_r1618923061_

**Comment by juliavdkris** [comment]
Whoops, didn't notice that you already created an issue. Closing this one, as #32 is a bit more descriptive and nicer formatted than my original comment on the PR :p
